### ISSUE TITLE
Logo For Stocks

### ISSUE THREAD

**Issue by zularizal** [pabhi66/Stocks#1]
Hi @pabhi66 , I am a graphic designer, I want to help you in graphic design.

After I review your project, your app is very good but this app does not yet have a logo. Therefore I suggest a  logo and icon for you. If you want it, I will design it for you and it's free.

**Comment by pabhi66** [comment]
Hi @zularizal, thank you for taking a look at my code. I really appreciate it. I'm working on this project just for my personal experience that uses all the new Android Arch. Also the app is in very early stage and I've no plan of publishing the app. However, if you like to contribute I would greatly appreciate it. Thank you again

**Comment by zularizal** [comment]
Hi @pabhi66 , this is the logo I have designed for your project, what do you think? Which one do you like? or if there is something part want to be changed please let me know

![logo](https://user-images.githubusercontent.com/38547278/41264017-991f44aa-6e14-11e8-8628-8641b4b866a7.png)

**Comment by pabhi66** [comment]
Hi @zularizal, wow this logos looks great. I would love to use one of these in the project with your permission.

**Comment by zularizal** [comment]
Which number do you like? It's free, I'll upload it to the drive and send it for you

**Comment by pabhi66** [comment]
the last one with green bar looks good. It also goes with the app theme (black, green, red).

**Comment by zularizal** [comment]
Hi #2 , i have uploaded logo file to drive, check this link

https://drive.google.com/open?id=1yJFuaA-ZLUiOw770KAdSBhwX7VEIxjWB

And i have sent you pull request #2
